### ISSUE TITLE
It stopped working with Google Cloud Functions.

### ISSUE THREAD

**Issue by fealone** [odd12258053/agraffe#12]
It stopped working with Google Cloud Functions after 2021-08-15 09:00.
I didn't change the application code at the occurrences time.

The occurrences error is below.

```
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/agraffe/__init__.py", line 38, in _entry_point4gcf return cls(app, GCPHttpCycle)(request=request) File "/env/local/lib/python3.7/site-packages/agraffe/__init__.py", line 27, in __call__ cycle(app=self.app) File "/env/local/lib/python3.7/site-packages/agraffe/services/base.py", line 21, in __call__ loop.run_until_complete(task) File "/opt/python3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete return future.result() File "/env/local/lib/python3.7/site-packages/agraffe/services/base.py", line 39, in run await app(self.scope, self.receive, self.send) File "/env/local/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__ await super().__call__(scope, receive, send) File "/env/local/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__ await self.middleware_stack(scope, receive, send) File "/env/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__ raise exc from None File "/env/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__ await self.app(scope, receive, _send) File "/env/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__ raise exc from None File "/env/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__ await self.app(scope, receive, sender) File "/env/local/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__ await route.handle(scope, receive, send) File "/env/local/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle await self.app(scope, receive, send) File "/env/local/lib/python3.7/site-packages/starlette/routing.py", line 52, in app response = await func(request) File "/env/local/lib/python3.7/site-packages/fastapi/routing.py", line 220, in app dependant=dependant, values=values, is_coroutine=is_coroutine File "/env/local/lib/python3.7/site-packages/fastapi/routing.py", line 152, in run_endpoint_function return await dependant.call(**values) File "/user_code/monitapi/__init__.py", line 28, in monitoring_with_get await watch() File "/user_code/monitapi/monitoring/monitor.py", line 178, in watch results = await asyncio.gather(*monitors) File "/user_code/monitapi/monitoring/monitor.py", line 81, in monitor_http response=await response.text() if response else error) File "/env/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1076, in text await self.read() File "/env/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1032, in read self._body = await self.content.read() File "/env/local/lib/python3.7/site-packages/aiohttp/streams.py", line 370, in read block = await self.readany() File "/env/local/lib/python3.7/site-packages/aiohttp/streams.py", line 392, in readany await self._wait("readany") File "/env/local/lib/python3.7/site-packages/aiohttp/streams.py", line 306, in _wait await waiter File "/env/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 656, in __exit__ raise asyncio.TimeoutError from None concurrent.futures._base.TimeoutError
```

**Comment by fealone** [comment]
It checked the issue today that it's resolved.
I think the issue is causing by Cloud Functions.
